### ISSUE TITLE
When something goes wrong with the state, there is no test output

### ISSUE THREAD

**Issue by wycats** [enokson/laboratory#2]
When the state fails to deserialize (because the types are wrong), there is no test output.

I just get the Cargo test run failure with no additional information:

![image](https://user-images.githubusercontent.com/4/97728966-69a50500-1a8f-11eb-8f29-d2d887051439.png)

**Comment by wycats** [comment]
It might be helpful if there was some way to explicitly annotate `describe` with the type of state. Without major changes, that might mean that `Suite` would become generic, and that there would be a way to pass an explicit type to `describe`, which would then need to match up in other methods that work with state.

One nice thing that might come from this sort of factoring: it would probably be possible to call the `it` blocks with the concrete state, rather than the state wrapper.

**Comment by enokson** [comment]
Hey, thank you for submitting your issue. I completely agree that explicitly annotating the suit with the type of state using generics would be helpful (and generally easier, simpler, more standard, and less verbose) and that was how it was originally written. However, I ran into an issue when nesting suites which have different types of state. The issue specifically is that the Suite stuct is recursive and whatever state type one assigns to the parent the child’s state type must be the same. Now, what Laboratory does to allow for differing types between parent suites and children is to serialize/deserialize the state into/from bin code. I would love to be able to explicitly annotate the suite with the state’s type. I just do not know how to do it while maintaining the nested suite’s freedom to have its own state type. I would also love to hear any suggestions, I have tried several different strategies, but I eventually hit a roadblock.
As for the issue of the error not being reported, would you mind submitting a snippet of your code so that I could reproduce the issue you have?

**Comment by enokson** [comment]
I will go ahead and work on the issue of the error not being reported by the compiler, but I want to express that I think the bigger victory would be to write the code as you suggested while maintaining the child suits’ freedom to have a different state type.

**Comment by wycats** [comment]
@enokson Thanks so much for all the feedback. I'll take a look at it and see if I can figure something out 😄

**Comment by enokson** [comment]
Once again, thank you for your feed back. I believe that I have resolved your issue. The fix is currently in the development branch. However, the fix is considered a breaking change, (although not a dramatic one) and so will require a major version bump. Before I push this to master and crates.io I am going to add a few more features I would like to see and also make one more breaking change to the should/should_not_panic macros which I feel are a little wonky in their syntax.

The reason I mention this is because now is a good opportunity to ask you and anyone else reading this if there are any features you would like to see added that would possibly cause further breaking changes.
thanks
